Repository audrasjb/wp-autoupdates, pull requests merged in 2020-03, with the labels that each got.

#35 Plugins screen: replace Automatic Updates with Auto-updates in filters
  wp-autoupdates.php
Labels: enhancement

#32 Remove setting from site option when deleting plugin
  wp-autoupdates.php
Labels: enhancement

#33 Plugins screen: Display only filters with at least one plugin
  wp-autoupdates.php
Labels: enhancement

#39 Plugins screen: Remove auto-updates column from mustuse and dropins screens
  wp-autoupdates.php
Labels: enhancement

#48 Add plugin_status query arg to the enable/disable links in the Automatic Updates column.
  wp-autoupdates.php
Labels: enhancement

#60 Fix some small internationalization inconsistencies introduced in 0.3.0
  wp-autoupdates.php
Labels: i18n

#44 Add themes autoupdates support basis
  wp-autoupdates.php
Labels: enhancement

#78 Further basis for themes auto-updates
  css/wp-autoupdates.css
  wp-autoupdates.php
Labels: enhancement

#83 Remove useless draft file
  wp-autoupdates-themes-draft.php
Labels: task

#82 Add Themes auto-updates to update-core.php screen
  css/wp-autoupdates.css
  wp-autoupdates.php
Labels: enhancement
